image: nkx1231/root6-geant4-garfield:0.6

variables:
#    GIT_SUBMODULE_STRATEGY: recursive

stages:
    # Basic checks to verify correctness of code
  - pre-build

    # Project compilation validation
  - build

    # REST libraries installed as sub-modules
  - libraries

    # Basic validation tests of installation
  - install

    # Basic core validation tests
  - core

    # Stage dedicated to validate metadata classes. gas, readout, g4Metadata, etc
  - metadata

    # Stage to validate restG4 package examples
  - restG4

    # Stage to validate data chain processing constructions (TREX-DM data, PandaX-III topology, etc).
  - restManager_process

    # Stage to validate tasks or executions over preprocessed data filesx
  - postProcessing

    # Stage to validate other restManager tasks (metadata generation, script loading, etc).
  - restManager_generate

    # Scripts to launch more complete tests. TRestGas file generation, Geant4 physics validation, etc.
  - deploy

before_script:
  - export USER="test"
    #  - export GIT_SSL_NO_VERIFY=1
  - echo $CI_SERVER_HOST
  - echo $CRONJOB
    # We redefine the HOME
  - export HOME=${CI_PROJECT_DIR}/install/
  - if [ -d $HOME/.rest ]; then rm -Rf $HOME/.rest; fi
  - pwd
  - root-config --version
  - geant4-config --version
  - python3 --version

clang-format:
  stage: pre-build
  script:

    - if [ $CI_SERVER_HOST != "lfna.unizar.es" ]; then exit 0; fi
    - cd ${CI_PROJECT_DIR}/
    - if [ -n "$CRONJOB" ]; then ./pipeline/clangformattest.sh; else echo "Skipping clang-format"; fi
    - ./pipeline/clangformattest.sh
    - clang-format --version
  only:
    variables:
      - $CI_SERVER_HOST == "lfna.unizar.es"
      - $CRONJOB
      - $CRONJOB == "YES"

validateCode:
    stage: pre-build
    script:
        - python ${CI_PROJECT_DIR}/pipeline/validateProcesses.py ${CI_PROJECT_DIR}/source/processes/
    except:
        variables:
            - $CRONJOB == "YES"

axionLib:
  stage: libraries
  script:
    - "curl -k -X POST -F token=bd53c38cdd1395ffeb14d297ebe202 -F ref=master https://lfna.unizar.es/api/v4/projects/31/trigger/pipeline"
  only:
      variables:
          - $CI_SERVER_HOST == "lfna.unizar.es"

modelLib:
  stage: libraries
  script:
    - "curl -k -X POST -F token=a244698329647e96d55908d75f3f0e -F ref=master https://lfna.unizar.es/api/v4/projects/11/trigger/pipeline"
  only:
      variables:
          - $CI_SERVER_HOST == "lfna.unizar.es"

build:
  type: build
  script:
    - cd ${CI_PROJECT_DIR}/
    - python3.5 pull-submodules.py --force --dontask
    - if [ -d ${CI_PROJECT_DIR}/build ]; then rm -Rf ${CI_PROJECT_DIR}/build; fi
    - mkdir ${CI_PROJECT_DIR}/build && cd ${CI_PROJECT_DIR}/build/
    - rm -rf ${CI_PROJECT_DIR}/install
    - cmake ${CI_PROJECT_DIR} -DREST_WELCOME=OFF -DREST_GARFIELD=ON -DREST_G4=ON -DRESTLIB_DETECTOR=ON -DRESTLIB_RAW=ON -DRESTLIB_TRACK=ON -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
  except:
      variables:
        - $CRONJOB == "YES"
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
    expire_in: 1 day

loadRESTLibs:
  type: install
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
      ### Produces segmentation fault :(
      #- root -b -q ${CI_PROJECT_DIR}/pipeline/loadLibraries.C
    - restRoot -b -q
  except:
      variables:
        - $CRONJOB == "YES"

listRESTMacros:
  type: install
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - restManager ListMacros
  except:
      variables:
        - $CRONJOB == "YES"

01_NLDBD:
  type: restG4
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples/01.NLDBD/
    - restG4 NLDBD.rml
    - geant4-config --version
    - restRoot -b -q Validate.C'("Run00001_NLDBD_Test.root")'
  except:
      variables:
        - $CRONJOB == "YES"
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/01.NLDBD/Run00001_NLDBD_Test.root
    expire_in: 1 day

02_PandaXiiiMC:
  type: restG4
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/pandaxiii_MC
    - restG4 Xe136bb0n.rml
    - restRoot -b -q ValidateG4.C'("Xe136bb0n_n2E06.root")'
  except:
      variables:
        - $CRONJOB == "YES"
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pipeline/pandaxiii_MC/Xe136bb0n_n2E06.root
    expire_in: 1 day

LoadGas:
  type: metadata 
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/metadata/gas/
    - restRoot -b -q LoadGasFromServerAndValidate.C
  only:
      variables:
        - $CI_SERVER_HOST == "lfna.unizar.es"
  except:
      variables:
        - $CRONJOB == "YES"

GenerateGas:
  type: metadata 
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/metadata/gas/
    - restRoot -b -q GenerateDummyGas.C
  only:
      variables:
        - $CI_SERVER_HOST == "lfna.unizar.es"
  except:
      variables:
        - $CRONJOB == "YES"

AnalysisTree:
  type: core
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/analysistree/
    - restRoot -b -q simpleTree.cpp
  except:
      variables:
        - $CRONJOB == "YES"

GenerateReadout:
  type: metadata 
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/metadata/readout/
    - restManager --c generateReadout.rml --o readout.root
    - restRoot -b -q PrintReadout.C'("readout.root")' > /dev/null
    - diff validation.txt print.txt
  only:
      variables:
        - $CI_SERVER_HOST == "lfna.unizar.es"
  except:
      variables:
        - $CRONJOB == "YES"

BasicReadout:
  type: metadata 
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/projects/basic-readouts/
    - ls
    - git status
    - git log
    - restRoot --m 1 -b -q GenerateReadouts.C'("basic.root")'
    - restRoot -b -q BasicValidation.C'("basic.root", "pixelDecoding")'
  only:
      variables:
        - $CI_SERVER_HOST == "lfna.unizar.es"       
  except:
      variables:
        - $CRONJOB == "YES"

testMeta:
  type: restManager_generate
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c saveMetadataFile.rml --o meta.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/meta.root
    expire_in: 1 day
  except:
      variables:
        - $CRONJOB == "YES"

trexDM_data: 
  type: restManager_process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/trex
    - wget https://sultan.unizar.es/trexdm-readouts/readouts_v2.3.root
    - cp R01928_tagTest_Vm380.aqs R01929_tagTest_Vm380.aqs
    - restManager --fork --c 01_raw.rml --f "*.aqs"
    - sleep 20
    - restManager --fork --c 02_signal.rml --f "RawData*.root"
    - sleep 20
    - restManager --fork --c 03_hits.rml --f "Signals*.root"
    - sleep 20
    - restRoot -b -q ../MakeBasicTree.C'("Hits_01928.root")'
    - rm RawData_01928.root
    - rm Signals_01928.root
    - root -b -q ../ValidateTrees.C'("validation.root")'
    - restRoot -b -q ../MakeBasicTree.C'("Hits_01929.root")'
    - rm RawData_01929.root
    - rm Signals_01929.root
    - root -b -q ../ValidateTrees.C'("validation.root")'
  except:
      variables:
        - $CRONJOB == "YES"

pandaXIII_Topological: 
  type: restManager_process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/pandaxiii_MC
    - restManager --c AllProcesses.rml --i testInput.root --o testOutput.root --j 1 --e 10
    - restRoot -b -q ../MakeBasicTree.C'("testOutput.root")'
    - restRoot -b -q ../ValidateTrees.C'("validation.root")'
    - restManager --c plots.rml --i testOutput.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pipeline/pandaxiii_MC/trackParameter.png
    expire_in: 1 week
  except:
      variables:
          - $CRONJOB

pandaXIII_Topological_fromG4: 
  type: restManager_process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/pandaxiii_MC
    - echo "using just-generated g4 file"
    - restManager --c AllProcesses.rml --i Xe136bb0n_n2E06.root --o testOutput.root --j 1 --e 10
    - restRoot -b -q ../MakeBasicTree.C'("testOutput.root")'
    - restRoot -b -q ../ValidateTrees.C'("validation.root")'
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pipeline/pandaxiii_MC/testOutput.root
    expire_in: 1 week
  except:
      variables:
        - $CRONJOB

pandaXIII_data: 
  type: restManager_process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/pandaxiii_data
    - restManager --c P3AutoChain.rml --i CoBo_AsAd0_2019-03-15.graw --o testOutput.root --j 1
    - restRoot -b -q ../MakeBasicTree.C'("testOutput.root")'
    - restRoot -b -q ../ValidateTrees.C'("validation.root")'
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pipeline/pandaxiii_data/TriggerRate.png
    expire_in: 1 week
  except:
      variables:
        - $CRONJOB
        
EventSelection: 
  type: restManager_process
  script:
    - restManager --c g4Analysis.rml --f "${CI_PROJECT_DIR}/install/examples/01.NLDBD/Run00001_NLDBD_Test.root"
    - restManager --c g4OnSelection.rml --f "${CI_PROJECT_DIR}/install/examples/01.NLDBD/Run00001_NLDBD_Test_g4Analysis.root"
    - restRoot -b -q ../Validate.C'("${CI_PROJECT_DIR}/install/examples/01.NLDBD/ExpectedOutput_NLDBD_Test_EvSelection.root")'
    
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/pipeline/selection/IDs.txt
    expire_in: 1 week
  except:
      variables:
        - $CRONJOB

AnalysisPlot:
  type: postProcessing
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/analysisPlot/
    - restManager --c summary.rml --f ${CI_PROJECT_DIR}/pipeline/trex/Hits.root
  except:
      variables:
        - $CRONJOB == "YES"

deploy:
  type: deploy
  only:
    - tags
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - rest-config --welcome
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
  except:
      variables:
        - $CRONJOB == "YES"
