name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  Check-Image:
    runs-on: ubuntu-latest
    container:
      image: lobis/root-geant4-garfieldpp:latest

    steps:
      - name: Check ROOT
        run: |
          root-config --version
          root-config --libs
          root-config --cflags

      - name: Check Geant4
        # TODO: We should run `geant4-config` but can't do it easily without interactive shell. This ENV variable is from the docker image
        run: |
          echo $GEANT4_VERSION
          ls -lht /opt/geant4/install

      # TODO: We should check that garfield is installed and working
      - name: Check Garfield++
        run: |
          ls -lht /opt/garfieldpp/install

  Build-Default:
    needs: Check-Image
    runs-on: ubuntu-latest
    env:
      REST_PATH: /opt/rest/install
    container:
      image: lobis/root-geant4-garfieldpp:latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull Submodules
        run: python3 pull-submodules.py

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          make install

      - name: REST config
        run: |
          ${REST_PATH}/bin/rest-config --version
          ${REST_PATH}/bin/rest-config --libs
          ${REST_PATH}/bin/rest-config --flags
          ${REST_PATH}/bin/rest-config --commit

  Build-Full:
    # TODO: install requiered dependencies so this job doesn't fail
    needs: Check-Image
    runs-on: ubuntu-latest
    env:
      REST_PATH: /opt/rest/install
    container:
      image: lobis/root-geant4-garfieldpp:latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull Submodules
        run: python3 pull-submodules.py

      - name: Build
        run: |
          export GARFIELD_HOME=/opt/garfieldpp/install
          mkdir -p build
          cd build
          cmake .. -DREST_ALL_LIBS=ON -DREST_G4=ON -DREST_GARFIELD=ON -DCMAKE_PREFIX_PATH=/opt/geant4/install
          make
          make install

      - name: REST config
        run: |
          ${REST_PATH}/bin/rest-config --version
          ${REST_PATH}/bin/rest-config --libs
          ${REST_PATH}/bin/rest-config --flags
          ${REST_PATH}/bin/rest-config --commit
